go-xcaddy:
  type: tool
  artifact:
    binary: custom
    install:
      destination: go-xcaddy
      root: go-xcaddy
      bin-dir: bin
  env:
    GOROOT: '{pkg_root_path}/go-xcaddy'
    GOBIN: '{pkg_root_path}/go-xcaddy/bin'
    GOPATH: '{pkg_root_path}/go-xcaddy/go'
  path@unix:
    - '{pkg_root_path}/go-xcaddy/bin'
  tool:
    provides:
      - go
      - gofmt
