protoc:
  type: tool
  artifact:
    binary:
      linux-x86_64: { type: ghrel, repo: protocolbuffers/protobuf, match: 'protoc-([0-9.]+)-linux-x86_64\.zip' }
      linux-aarch64: { type: ghrel, repo: protocolbuffers/protobuf, match: 'protoc-([0-9.]+)-linux-aarch_64\.zip' }
    install:
      destination: protoc
      root: protoc
  path:
    - '{pkg_root_path}/protoc/bin'
  tool:
    provides:
      - protoc
