zig:
  type: tool
  artifact:
    binary: custom
    install:
      destination: zig
      root: zig
      bin-dir: ''
  tool:
    provides:
      - zig
      - zig-cc
      - zig-c++
      - zig-ar
      - zig-ld.lld
      - zig-ranlib
      - zig-objcopy
